name: Auto Setup and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python Modules
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4  # Add your required Python packages here

      - name: Run Python Script
        run: |
          python start.py  # Replace this with your script to generate files

      - name: Ensure Git Repository Initialization
        run: |
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if git rev-parse --verify main; then
            git checkout main
          else
            git checkout -b main
          fi

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Auto-generated files by GitHub Actions"
          git remote add origin https://github.com/<your-username>/<your-repo>.git
          git push --set-upstream origin main --force
