name: Auto Setup and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  workflow_dispatch:  # This allows the workflow to be triggered manually via GitHub's interface

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (adjust the Python version as needed)
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # You can change this version if needed

      # Step 3: Install required Python modules
      - name: Install Python Modules
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4  # Replace with the libraries your script needs

      # Step 4: Run the Python script (start.py) to generate files
      - name: Run Python script to generate files
        run: |
          python start.py  # Run your start.py script to create files

      # Step 5: Commit and push changes back to GitHub
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-generated files by GitHub Actions"
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: setup  # This ensures the deploy job runs after the setup job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Optional Step: Deploy to GitHub Pages (if needed)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Change this if you want to deploy to a different branch
          folder: .  # The folder where your generated files are located (e.g., root or build folder)
